version: 2
services:
  web:
    image: carloshspereira/fiaptech_chalenge_web:latest
    resources:
      cpu: 1000
      memory: 1024
    ports:
      - "80"
    environment:
      - SERVER=172.17.0.1
      - USER=ta
      - PASSWORD=jklhb#8239
      - DATABASE=techchallengeDB
    depends_on:
      db:
        condition: service_started
  db:
    image: carloshspereira/fiaptech_chalenge_db:latest
    environment:
      - POSTGRES_USER=ta
      - POSTGRES_PASSWORD=jklhb#8239
      - POSTGRES_DB=techchallengeDB
    ports:
      - "5432:5432"
    resources:
      cpu: 500
      memory: 512
    volumes:
      - db_data
volumes:
  db_data:
